/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package KiemTra;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FPT
 */
public class Cau1 extends javax.swing.JFrame {

    DefaultTableModel defaultTableModel = new DefaultTableModel();

    private void KhoiTaoDuLieu() {
        defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("Họ tên");
        defaultTableModel.addColumn("Que quan");
        
        Object[] row1 = { "Nguyễn An", "Thanh Hoa"};
        defaultTableModel.addRow(row1);
       Object[] row2 = { " An", "Thanh Hoa"};
        defaultTableModel.addRow(row2);
        Object[] row3 = { "Nguyễn ", "Thanh Hoa"};
        defaultTableModel.addRow(row3);
        Object[] row4 = { "Nguyễn ", "Thanh "};
        defaultTableModel.addRow(row4);
        tbThongTinCaNhan.setModel(defaultTableModel);
    }
     private void resetControll() {
       
        txtHoTenThem.setText("");
        comboboxQueQuanThem.setSelectedItem(0);
        
        txtSuaHoTen.setText("");
        comboboxSuaQueQuan.setSelectedItem(0);
    }

    /**
     * Creates ne
     */
    public Cau1() {
        initComponents();
        KhoiTaoDuLieu();
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diaglogThemThongTin = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHoTenThem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboboxQueQuanThem = new javax.swing.JComboBox<>();
        btDongYThem = new javax.swing.JButton();
        btHuyBoThem = new javax.swing.JButton();
        dialogSuaThongTin = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSuaHoTen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comboboxSuaQueQuan = new javax.swing.JComboBox<>();
        btSuaDongY = new javax.swing.JButton();
        btSuaHuyBo = new javax.swing.JButton();
        dialogXoaThongTin = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtXoaHoTen = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        comboboxXoaQueQuan = new javax.swing.JComboBox<>();
        btXoaDongY = new javax.swing.JButton();
        btXoaHuyBo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btThoat = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbThongTinCaNhan = new javax.swing.JTable();

        diaglogThemThongTin.setTitle("Thêm thông tin");
        diaglogThemThongTin.setSize(new java.awt.Dimension(350, 200));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("THÊM THÔNG TIN CÁ NHÂN");

        jLabel3.setText("Họ và tên:");

        jLabel4.setText("Quê quán");

        comboboxQueQuanThem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hà Nội", "Thanh Hóa", "Đà Nẵng", "HCM", " " }));

        btDongYThem.setText("Đồng ý");
        btDongYThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDongYThemActionPerformed(evt);
            }
        });

        btHuyBoThem.setText("Hủy bỏ");
        btHuyBoThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHuyBoThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diaglogThemThongTinLayout = new javax.swing.GroupLayout(diaglogThemThongTin.getContentPane());
        diaglogThemThongTin.getContentPane().setLayout(diaglogThemThongTinLayout);
        diaglogThemThongTinLayout.setHorizontalGroup(
            diaglogThemThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaglogThemThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diaglogThemThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(diaglogThemThongTinLayout.createSequentialGroup()
                        .addGroup(diaglogThemThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(diaglogThemThongTinLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(diaglogThemThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHoTenThem, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboboxQueQuanThem, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(diaglogThemThongTinLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btDongYThem)
                .addGap(18, 18, 18)
                .addComponent(btHuyBoThem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        diaglogThemThongTinLayout.setVerticalGroup(
            diaglogThemThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaglogThemThongTinLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(diaglogThemThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHoTenThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(diaglogThemThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboboxQueQuanThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(diaglogThemThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDongYThem)
                    .addComponent(btHuyBoThem))
                .addGap(0, 62, Short.MAX_VALUE))
        );

        dialogSuaThongTin.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        dialogSuaThongTin.setTitle("Sửa thông tin");
        dialogSuaThongTin.setAlwaysOnTop(true);
        dialogSuaThongTin.setSize(new java.awt.Dimension(300, 200));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SỬA THÔNG TIN CÁ NHÂN");

        jLabel6.setText("Họ và tên:");

        jLabel7.setText("Quê quán");

        comboboxSuaQueQuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hà Nội", "Thanh Hóa", "Đà Nẵng", "HCM", " " }));

        btSuaDongY.setText("Đồng ý");
        btSuaDongY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaDongYActionPerformed(evt);
            }
        });

        btSuaHuyBo.setText("Hủy bỏ");
        btSuaHuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaHuyBoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogSuaThongTinLayout = new javax.swing.GroupLayout(dialogSuaThongTin.getContentPane());
        dialogSuaThongTin.getContentPane().setLayout(dialogSuaThongTinLayout);
        dialogSuaThongTinLayout.setHorizontalGroup(
            dialogSuaThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogSuaThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogSuaThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(dialogSuaThongTinLayout.createSequentialGroup()
                        .addGroup(dialogSuaThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialogSuaThongTinLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(dialogSuaThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSuaHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboboxSuaQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 86, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(dialogSuaThongTinLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btSuaDongY)
                .addGap(18, 18, 18)
                .addComponent(btSuaHuyBo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogSuaThongTinLayout.setVerticalGroup(
            dialogSuaThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogSuaThongTinLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogSuaThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSuaHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogSuaThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboboxSuaQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(dialogSuaThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSuaDongY)
                    .addComponent(btSuaHuyBo))
                .addGap(0, 94, Short.MAX_VALUE))
        );

        dialogXoaThongTin.setTitle("Sửa thông tin");
        dialogXoaThongTin.setModal(true);
        dialogXoaThongTin.setSize(new java.awt.Dimension(300, 200));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("XÓA THÔNG TIN CÁ NHÂN");

        jLabel9.setText("Họ và tên:");

        jLabel10.setText("Quê quán");

        comboboxXoaQueQuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hà Nội", "Thanh Hóa", "Đà Nẵng", "HCM", " " }));

        btXoaDongY.setText("Đồng ý");
        btXoaDongY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaDongYActionPerformed(evt);
            }
        });

        btXoaHuyBo.setText("Hủy bỏ");
        btXoaHuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaHuyBoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogXoaThongTinLayout = new javax.swing.GroupLayout(dialogXoaThongTin.getContentPane());
        dialogXoaThongTin.getContentPane().setLayout(dialogXoaThongTinLayout);
        dialogXoaThongTinLayout.setHorizontalGroup(
            dialogXoaThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogXoaThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogXoaThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(dialogXoaThongTinLayout.createSequentialGroup()
                        .addGroup(dialogXoaThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialogXoaThongTinLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(dialogXoaThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtXoaHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboboxXoaQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 86, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(dialogXoaThongTinLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btXoaDongY)
                .addGap(18, 18, 18)
                .addComponent(btXoaHuyBo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogXoaThongTinLayout.setVerticalGroup(
            dialogXoaThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogXoaThongTinLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogXoaThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtXoaHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogXoaThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comboboxXoaQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(dialogXoaThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btXoaDongY)
                    .addComponent(btXoaHuyBo))
                .addGap(0, 169, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DS thông tin cá nhân");
        setPreferredSize(new java.awt.Dimension(350, 400));
        setResizable(false);

        jLabel1.setText("DANH SÁCH THÔNG TIN CÁ NHÂN");

        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btSua.setText("Sửa");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        btXoa.setText("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btThoat.setText("Thoát");
        btThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoatActionPerformed(evt);
            }
        });

        tbThongTinCaNhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        tbThongTinCaNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbThongTinCaNhanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbThongTinCaNhan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btThem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btSua)
                                .addGap(18, 18, 18)
                                .addComponent(btXoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btThoat))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(346, 346, 346))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSua)
                    .addComponent(btXoa)
                    .addComponent(btThoat)
                    .addComponent(btThem))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
        // TODO add your handling code here:
         int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btThoatActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
       diaglogThemThongTin.setTitle("Thêm thông tin");
        diaglogThemThongTin.setLocationRelativeTo(null);
        diaglogThemThongTin.setVisible(true);
    }//GEN-LAST:event_btThemActionPerformed

    private void btDongYThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDongYThemActionPerformed
        // TODO add your handling code here 
        Object[] rowi = {  txtHoTenThem.getText(),comboboxQueQuanThem.getSelectedItem().toString() };
        defaultTableModel.addRow(rowi);
        tbThongTinCaNhan.clearSelection();
        resetControll();
        diaglogThemThongTin.setVisible(false);
    }//GEN-LAST:event_btDongYThemActionPerformed

    private void btHuyBoThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHuyBoThemActionPerformed
        // TODO add your handling code here:
         tbThongTinCaNhan.clearSelection();
        resetControll();
        diaglogThemThongTin.setVisible(false);
    }//GEN-LAST:event_btHuyBoThemActionPerformed
 int chisodong = -1;
 
    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
        if (chisodong >= 0) {
           
            txtSuaHoTen.setText(tbThongTinCaNhan.getModel().
                    getValueAt(chisodong, 0).toString());
            comboboxSuaQueQuan.setSelectedItem(tbThongTinCaNhan.getModel().
                    getValueAt(chisodong, 1).toString());
           
        }
        dialogSuaThongTin.setTitle("Sửa thông tin");
        dialogSuaThongTin.setLocationRelativeTo(null);
        dialogSuaThongTin.setVisible(true);
    }//GEN-LAST:event_btSuaActionPerformed

    private void tbThongTinCaNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbThongTinCaNhanMouseClicked
        // TODO add your handling code here:
        chisodong = tbThongTinCaNhan.getSelectedRow();
    }//GEN-LAST:event_tbThongTinCaNhanMouseClicked

    private void btSuaDongYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaDongYActionPerformed
        // TODO add your handling code here:
        if (chisodong >= 0) {
            defaultTableModel.setValueAt(txtSuaHoTen.getText(), chisodong, 0);
            defaultTableModel.setValueAt(comboboxSuaQueQuan.getSelectedItem(), chisodong, 1);

            tbThongTinCaNhan.setModel(defaultTableModel);
            tbThongTinCaNhan.clearSelection();
            resetControll();
            chisodong = -1;
            dialogSuaThongTin.setVisible(false);
        }
    }//GEN-LAST:event_btSuaDongYActionPerformed

    private void btSuaHuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaHuyBoActionPerformed
        // TODO add your handling code here:
        tbThongTinCaNhan.clearSelection();
        resetControll();
        chisodong = -1;
        dialogSuaThongTin.setVisible(false);
    }//GEN-LAST:event_btSuaHuyBoActionPerformed

    private void btXoaDongYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaDongYActionPerformed
        // TODO add your handling code here:
         String str = tbThongTinCaNhan.getModel().getValueAt(chisodong, 0).toString();
        int confirm = JOptionPane.showConfirmDialog(this,
                "Bạn chắc chắn muốn xóa bản ghi: \n" + str, "Confirm", JOptionPane.YES_NO_OPTION
        );
        if (confirm == JOptionPane.YES_OPTION) {
            defaultTableModel.removeRow(chisodong);
            tbThongTinCaNhan.setModel(defaultTableModel);
            chisodong = -1;
            tbThongTinCaNhan.clearSelection();
            resetControll();
            chisodong = -1;
            dialogXoaThongTin.setVisible(false);
        }
    }//GEN-LAST:event_btXoaDongYActionPerformed

    private void btXoaHuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaHuyBoActionPerformed
        // TODO add your handling code here:
        tbThongTinCaNhan.clearSelection();
        resetControll();
        chisodong = -1;
        dialogXoaThongTin.setVisible(false);
    }//GEN-LAST:event_btXoaHuyBoActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        if (chisodong >= 0) {
           
            txtXoaHoTen.setText(tbThongTinCaNhan.getModel().
                    getValueAt(chisodong, 0).toString());
            comboboxXoaQueQuan.setSelectedItem(tbThongTinCaNhan.getModel().
                    getValueAt(chisodong, 1).toString());
           
        }
        dialogXoaThongTin.setTitle("Xoa thông tin");
        dialogXoaThongTin.setLocationRelativeTo(null);
        dialogXoaThongTin.setVisible(true);
    }//GEN-LAST:event_btXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cau1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cau1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cau1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cau1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cau1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDongYThem;
    private javax.swing.JButton btHuyBoThem;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btSuaDongY;
    private javax.swing.JButton btSuaHuyBo;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btThoat;
    private javax.swing.JButton btXoa;
    private javax.swing.JButton btXoaDongY;
    private javax.swing.JButton btXoaHuyBo;
    private javax.swing.JComboBox<String> comboboxQueQuanThem;
    private javax.swing.JComboBox<String> comboboxSuaQueQuan;
    private javax.swing.JComboBox<String> comboboxXoaQueQuan;
    private javax.swing.JDialog diaglogThemThongTin;
    private javax.swing.JDialog dialogSuaThongTin;
    private javax.swing.JDialog dialogXoaThongTin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tbThongTinCaNhan;
    private javax.swing.JTextField txtHoTenThem;
    private javax.swing.JTextField txtSuaHoTen;
    private javax.swing.JTextField txtXoaHoTen;
    // End of variables declaration//GEN-END:variables
}
