/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ThucHanh3;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FPT
 */
public class Bai3 extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    public Bai3() {
        initComponents();
        KhoiTaoDuLieu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogThem = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        txtmaSVThem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHoTenThem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDienThoaiThem = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmailThem = new javax.swing.JTextField();
        btDongY = new javax.swing.JButton();
        btHuyBo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        dialogSua = new javax.swing.JDialog();
        txtmaSVSua = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHoTenSua = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDienThoaiSua = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmailSua = new javax.swing.JTextField();
        btDongYSua = new javax.swing.JButton();
        btHuyBoSua = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSSinhVien = new javax.swing.JTable();
        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        dialogThem.setTitle("Them thong tin");
        dialogThem.setModal(true);
        dialogThem.setSize(new java.awt.Dimension(250, 350));

        jLabel2.setText("Ma sinh vien");

        jLabel3.setText("Ho va Ten");

        jLabel4.setText("Dien Thoai");

        txtDienThoaiThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDienThoaiThemActionPerformed(evt);
            }
        });

        jLabel5.setText("Email");

        btDongY.setText("Dong y");
        btDongY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDongYActionPerformed(evt);
            }
        });

        btHuyBo.setText("Huy bo");
        btHuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHuyBoActionPerformed(evt);
            }
        });

        jLabel10.setText("Thêm");

        javax.swing.GroupLayout dialogThemLayout = new javax.swing.GroupLayout(dialogThem.getContentPane());
        dialogThem.getContentPane().setLayout(dialogThemLayout);
        dialogThemLayout.setHorizontalGroup(
            dialogThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogThemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogThemLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(dialogThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialogThemLayout.createSequentialGroup()
                                .addComponent(txtEmailThem, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 24, Short.MAX_VALUE))
                            .addGroup(dialogThemLayout.createSequentialGroup()
                                .addComponent(btDongY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btHuyBo))))
                    .addGroup(dialogThemLayout.createSequentialGroup()
                        .addGroup(dialogThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dialogThemLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                            .addComponent(txtDienThoaiThem, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addGroup(dialogThemLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtHoTenThem)
                            .addComponent(txtmaSVThem)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(39, 39, 39))
        );
        dialogThemLayout.setVerticalGroup(
            dialogThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogThemLayout.createSequentialGroup()
                .addGroup(dialogThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogThemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmaSVThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHoTenThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDienThoaiThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmailThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(dialogThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDongY)
                    .addComponent(btHuyBo))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        dialogSua.setTitle("Sua thong tin");
        dialogSua.setModal(true);
        dialogSua.setSize(new java.awt.Dimension(250, 350));

        jLabel6.setText("Ho va Ten");

        jLabel7.setText("Dien Thoai");

        txtDienThoaiSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDienThoaiSuaActionPerformed(evt);
            }
        });

        jLabel8.setText("Email");

        btDongYSua.setText("Dong y Sua");
        btDongYSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDongYSuaActionPerformed(evt);
            }
        });

        btHuyBoSua.setText("Huy bo");
        btHuyBoSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHuyBoSuaActionPerformed(evt);
            }
        });

        jLabel9.setText("Ma sinh vien");

        jLabel11.setText("sửa");

        javax.swing.GroupLayout dialogSuaLayout = new javax.swing.GroupLayout(dialogSua.getContentPane());
        dialogSua.getContentPane().setLayout(dialogSuaLayout);
        dialogSuaLayout.setHorizontalGroup(
            dialogSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogSuaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogSuaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(dialogSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmailSua, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dialogSuaLayout.createSequentialGroup()
                                .addComponent(btDongYSua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                                .addComponent(btHuyBoSua)))
                        .addGap(114, 114, 114))
                    .addGroup(dialogSuaLayout.createSequentialGroup()
                        .addGroup(dialogSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDienThoaiSua, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addGroup(dialogSuaLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtHoTenSua)
                            .addComponent(txtmaSVSua)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))))
        );
        dialogSuaLayout.setVerticalGroup(
            dialogSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogSuaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmaSVSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHoTenSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDienThoaiSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmailSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(dialogSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDongYSua)
                    .addComponent(btHuyBoSua))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUAN LY SINH VIEN");

        tblDSSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblDSSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSSinhVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSSinhVien);

        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btSua.setText("Sửa");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        btXoa.setText("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btReset.setText("Reset");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });

        btExit.setText("Exit");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btThem)
                                        .addGap(18, 18, 18)
                                        .addComponent(btSua)
                                        .addGap(18, 18, 18)
                                        .addComponent(btXoa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btReset)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btExit)
                                        .addGap(0, 15, Short.MAX_VALUE)))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThem)
                    .addComponent(btSua)
                    .addComponent(btXoa)
                    .addComponent(btReset)
                    .addComponent(btExit))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
DefaultTableModel defaultTableModel = new DefaultTableModel();

    private void KhoiTaoDuLieu() {
        defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("TT");
        defaultTableModel.addColumn("Mã SV");
        defaultTableModel.addColumn("Họ tên");
        defaultTableModel.addColumn("Điện thoai");
        defaultTableModel.addColumn("Email");
        Object[] row1 = {"1", "01", "Nguyễn An", "0912345678", "a@gmail.com"};
        defaultTableModel.addRow(row1);
        Object[] row2 = {"2", "02", "Quách Tĩnh", "0912345679", "b@gmail.com"};
        defaultTableModel.addRow(row2);
        Object[] row3 = {"3", "03", "Hoàng Dung", "0912345978", "c@gmail.com"};
        defaultTableModel.addRow(row3);
        tblDSSinhVien.setModel(defaultTableModel);
    }

    private void resetControll() {
        txtmaSVThem.setText("");
        txtHoTenThem.setText("");
        txtDienThoaiThem.setText("");
        txtEmailThem.setText("");
        
        txtmaSVSua.setText("");
        txtHoTenSua.setText("");
        txtDienThoaiSua.setText("");
        txtEmailSua.setText("");
    }
    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
        dialogThem.setTitle("Thêm thông tin");
        dialogThem.setLocationRelativeTo(null);
        dialogThem.setVisible(true);
    }//GEN-LAST:event_btThemActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btExitActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        // TODO add your handling code here:
        KhoiTaoDuLieu();
        resetControll();
    }//GEN-LAST:event_btResetActionPerformed

    private void txtDienThoaiThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDienThoaiThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDienThoaiThemActionPerformed

    private void btDongYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDongYActionPerformed
        // TODO add your handling code here:
        int i = defaultTableModel.getRowCount() + 1;
        Object[] rowi = {i, txtmaSVThem.getText(), txtHoTenThem.getText(), txtDienThoaiThem.getText(), txtEmailThem.getText()};
        defaultTableModel.addRow(rowi);
        tblDSSinhVien.clearSelection();
        resetControll();
        dialogThem.setVisible(false);
    }//GEN-LAST:event_btDongYActionPerformed

    private void btHuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHuyBoActionPerformed
        // TODO add your handling code here:
        tblDSSinhVien.clearSelection();
        resetControll();
        dialogThem.setVisible(false);
    }//GEN-LAST:event_btHuyBoActionPerformed
    int chisodong = -1;
    private void tblDSSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSSinhVienMouseClicked
        // TODO add your handling code here:
        chisodong = tblDSSinhVien.getSelectedRow();
    }//GEN-LAST:event_tblDSSinhVienMouseClicked

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
        if (chisodong >= 0) {
            txtmaSVSua.setText(tblDSSinhVien.getModel().getValueAt(chisodong, 1).toString());
            txtHoTenSua.setText(tblDSSinhVien.getModel().
                    getValueAt(chisodong, 2).toString());
            txtDienThoaiSua.setText(String.valueOf(tblDSSinhVien.getModel().getValueAt(chisodong,3)));
            txtEmailSua.setText(String.valueOf(tblDSSinhVien.getModel().
                    getValueAt(chisodong, 4)));
        }
        dialogSua.setTitle("Sửa thông tin");
        dialogSua.setLocationRelativeTo(null);
        dialogSua.setVisible(true);
    }//GEN-LAST:event_btSuaActionPerformed

    private void txtDienThoaiSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDienThoaiSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDienThoaiSuaActionPerformed

    private void btDongYSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDongYSuaActionPerformed
        // TODO add your handling code here:
        if (chisodong >= 0) {
            defaultTableModel.setValueAt(txtmaSVSua.getText(), chisodong, 1);
            defaultTableModel.setValueAt(txtHoTenSua.getText(), chisodong, 2);
            defaultTableModel.setValueAt(txtDienThoaiSua.getText(),chisodong, 3);
            defaultTableModel.setValueAt(txtEmailSua.getText(), chisodong, 4);
            tblDSSinhVien.setModel(defaultTableModel);
            tblDSSinhVien.clearSelection();
            resetControll();
            chisodong = -1;
            dialogSua.setVisible(false);
        }
    }//GEN-LAST:event_btDongYSuaActionPerformed

    private void btHuyBoSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHuyBoSuaActionPerformed
        // TODO add your handling code here:
        tblDSSinhVien.clearSelection();
        resetControll();
        chisodong = -1;
        dialogSua.setVisible(false);
    }//GEN-LAST:event_btHuyBoSuaActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        String str = tblDSSinhVien.getModel().
                getValueAt(chisodong, 2).toString();
        int confirm = JOptionPane.showConfirmDialog(this,
                "Bạn chắc chắn muốn xóa bản ghi: \n" + str, "Confirm", JOptionPane.YES_NO_OPTION
        );
        if (confirm == JOptionPane.YES_OPTION) {
            defaultTableModel.removeRow(chisodong);
            tblDSSinhVien.setModel(defaultTableModel);
            chisodong = -1;
            tblDSSinhVien.clearSelection();
            resetControll();
        }
    }//GEN-LAST:event_btXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDongY;
    private javax.swing.JButton btDongYSua;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btHuyBo;
    private javax.swing.JButton btHuyBoSua;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btXoa;
    private javax.swing.JDialog dialogSua;
    private javax.swing.JDialog dialogThem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblDSSinhVien;
    private javax.swing.JTextField txtDienThoaiSua;
    private javax.swing.JTextField txtDienThoaiThem;
    private javax.swing.JTextField txtEmailSua;
    private javax.swing.JTextField txtEmailThem;
    private javax.swing.JTextField txtHoTenSua;
    private javax.swing.JTextField txtHoTenThem;
    private javax.swing.JTextField txtmaSVSua;
    private javax.swing.JTextField txtmaSVThem;
    // End of variables declaration//GEN-END:variables
}
