/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ThucHanh3;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author FPT
 */
public class Bai5 extends javax.swing.JFrame {

    /**
     * Creates new form Bai5
     */
    public Bai5() {
        initComponents();
        KhoiTaoDuLieu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btTongCacPT = new javax.swing.JButton();
        btXoaPTDauCuoi = new javax.swing.JButton();
        btXoaPhanTuDangChon = new javax.swing.JButton();
        btTang2DonVi = new javax.swing.JButton();
        btThayBangBinhPhuong = new javax.swing.JButton();
        btChonSoChan = new javax.swing.JButton();
        btChonSoLe = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtSo = new javax.swing.JTextField();
        btNhap = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listSo = new javax.swing.JList<>();
        btReset = new javax.swing.JButton();
        btExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("THAO  TAC TREN JLIST");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chon tac vu"));

        btTongCacPT.setText("Tong cac phan tu trong list");
        btTongCacPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTongCacPTActionPerformed(evt);
            }
        });

        btXoaPTDauCuoi.setText("Xoa cac phan tu dau va cuoi");
        btXoaPTDauCuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaPTDauCuoiActionPerformed(evt);
            }
        });

        btXoaPhanTuDangChon.setText("Xoa cac phan tu dang chon");
        btXoaPhanTuDangChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaPhanTuDangChonActionPerformed(evt);
            }
        });

        btTang2DonVi.setText("Tang moi phan tu len 2 don vi");
        btTang2DonVi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTang2DonViActionPerformed(evt);
            }
        });

        btThayBangBinhPhuong.setText("Thay bang binh phuong");
        btThayBangBinhPhuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThayBangBinhPhuongActionPerformed(evt);
            }
        });

        btChonSoChan.setText("Chon so chan");
        btChonSoChan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChonSoChanActionPerformed(evt);
            }
        });

        btChonSoLe.setText("Chon so le");
        btChonSoLe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChonSoLeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btChonSoLe)
                    .addComponent(btChonSoChan)
                    .addComponent(btThayBangBinhPhuong)
                    .addComponent(btTang2DonVi)
                    .addComponent(btXoaPhanTuDangChon)
                    .addComponent(btXoaPTDauCuoi)
                    .addComponent(btTongCacPT))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btTongCacPT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btXoaPTDauCuoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btXoaPhanTuDangChon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btTang2DonVi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btThayBangBinhPhuong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btChonSoChan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btChonSoLe)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Du lieu"));

        btNhap.setText("Nhap");
        btNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNhapActionPerformed(evt);
            }
        });

        listSo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listSo);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNhap)
                    .addComponent(txtSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btReset.setText("Reset");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });

        btExit.setText("Exit");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btExit)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btReset)
                    .addComponent(btExit))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DefaultListModel listModel = new DefaultListModel();

    private void KhoiTaoDuLieu() {
        listSo.setModel(listModel);
    }
    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btExitActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        // TODO add your handling code here:
        txtSo.setText("");
        listModel = new DefaultListModel();
        listSo.setModel(listModel);
    }//GEN-LAST:event_btResetActionPerformed

    private void btTongCacPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTongCacPTActionPerformed
        // TODO add your handling code here:
        int tong = 0;
        for (int i = 0; i < listSo.getModel().getSize(); i++) {
            tong += Integer.parseInt(listModel.getElementAt(i).toString());
        }
        JOptionPane.showMessageDialog(this, "Tổng các phần tử: " + tong, "Information",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btTongCacPTActionPerformed

    private void btXoaPTDauCuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaPTDauCuoiActionPerformed
        // TODO add your handling code here:
        if (listModel.getSize() == 1) {
            int confirm = JOptionPane.showConfirmDialog(null,
                    "Chỉ có 1 phần tử, bạn chắc chắn xóa?", "Information", JOptionPane.OK_CANCEL_OPTION);
            if (confirm == JOptionPane.OK_OPTION) {
                listModel.remove(0);
            }
        } else if (listModel.getSize() > 1) {
            int confirm = JOptionPane.showConfirmDialog(null,
                    "Chắc chắn muốn xóa phần tử đầu và cuối", "Information", JOptionPane.OK_CANCEL_OPTION);
            if (confirm == JOptionPane.OK_OPTION) {
                listModel.remove(listModel.getSize() - 1);
                listModel.remove(0);
            }
        } else if (listModel.getSize() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Không có phần tử nào trong list", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btXoaPTDauCuoiActionPerformed

    private void btXoaPhanTuDangChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaPhanTuDangChonActionPerformed
        // TODO add your handling code here:
        if (this.listSo.getSelectedIndices().length > 0) {
            int[] selectedIndices = this.listSo.getSelectedIndices();
            for (int i = selectedIndices.length - 1; i >= 0; i--) {
                listModel.removeElementAt(selectedIndices[i]);
            }
        }
    }//GEN-LAST:event_btXoaPhanTuDangChonActionPerformed

    private void btTang2DonViActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTang2DonViActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < listModel.getSize(); i++) {
            listModel.setElementAt(Integer.valueOf(listModel.getElementAt(i).toString()) + 2, i);
        }
    }//GEN-LAST:event_btTang2DonViActionPerformed

    private void btThayBangBinhPhuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThayBangBinhPhuongActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < listModel.getSize(); i++) {
            int a = Integer.valueOf(listModel.getElementAt(i).toString());
            listModel.setElementAt(a * a, i);
        }
    }//GEN-LAST:event_btThayBangBinhPhuongActionPerformed

    private void btChonSoChanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChonSoChanActionPerformed
        // TODO add your handling code here:
        listSo.clearSelection();
        for (int i = 0; i < listSo.getModel().getSize(); i++) {
            int a = Integer.valueOf(listModel.getElementAt(i).toString());
            if (a % 2 == 0) {
                this.listSo.addSelectionInterval(i, i);
            }
        }
    }//GEN-LAST:event_btChonSoChanActionPerformed

    private void btChonSoLeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChonSoLeActionPerformed
        // TODO add your handling code here:
        listSo.clearSelection();
        for (int i = 0; i < listSo.getModel().getSize(); i++) {
            int a = Integer.valueOf(listModel.getElementAt(i).toString());
            if (a % 2 != 0) {
                this.listSo.addSelectionInterval(i, i);
            }
        }
    }//GEN-LAST:event_btChonSoLeActionPerformed

    private void btNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNhapActionPerformed
        // TODO add your handling code here:
        if (txtSo.getText().equals("")) {
            JOptionPane.showMessageDialog(null,
                    "Bạn phải nhập dữ liệu cho ô text !",
                    "Error", JOptionPane.ERROR_MESSAGE);
            txtSo.requestFocus();
        } else {
            int numberi;
            try {
                numberi = Integer.parseInt(txtSo.getText().trim());
                listModel.addElement(numberi);
                txtSo.setText("");
                txtSo.requestFocus();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Dữ liệu không đúng.",
                        "Error", JOptionPane.OK_CANCEL_OPTION);
                txtSo.setText("");
                txtSo.requestFocus();
            }
        }
    }//GEN-LAST:event_btNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btChonSoChan;
    private javax.swing.JButton btChonSoLe;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btNhap;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btTang2DonVi;
    private javax.swing.JButton btThayBangBinhPhuong;
    private javax.swing.JButton btTongCacPT;
    private javax.swing.JButton btXoaPTDauCuoi;
    private javax.swing.JButton btXoaPhanTuDangChon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listSo;
    private javax.swing.JTextField txtSo;
    // End of variables declaration//GEN-END:variables
}
